name: Test include syntax

on: 
  push:
    paths:
    - '/*'
    - '.github/workflows/test_include_syntax.yml'

jobs:

  test-exclude:
    runs-on: ubuntu-latest
    name: "Unity-build: ${{ matrix.UNITY_BUILD }}, C++ testing: ${{ matrix.BUILD_TESTING }}"
    
    strategy:
      fail-fast: false
      matrix:
        UNITY_BUILD: [ON, OFF]
        BUILD_TESTING: [ON, OFF]
        exclude:
          # this is in the main CI
          - UNITY_BUILD: ON
            BUILD_TESTING: ON

    steps:
    - uses: actions/checkout@v2

    - name: Step 1
      run:  |
        echo "UNITY_BUILD: " ${{ matrix.unity_build }}
        echo "CPP_TESTS: " ${{ matrix.cpp_tests }}
