name: Test Docker with ENTRYPOINT

on: push

jobs:

  create-docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |

        docker build . --file .github/basic-docker-with-entrypoint/DockerFile \
          --tag philbucher/basic-docker-with-entrypoint

    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish the Docker image
      run: docker push philbucher/basic-docker-with-entrypoint


  test-docker:
    needs: create-docker

    runs-on: ubuntu-latest

    container:
      image: philbucher/basic-docker-with-entrypoint:latest
      options: "--entrypoint /bin/bash"

    steps:
    - uses: actions/checkout@v2

    - name: Step 1
      run: echo "Hello from Step 1"

    - name: Step 2
      run: echo "Hello from Step 2"
